// This file was generated by py/makeversionhdr.py
#define MICROPY_GIT_TAG "v1.9.1-69-ga9261190-dirty"
#define MICROPY_GIT_HASH "a9261190-dirty"
#define MICROPY_BUILD_DATE "2017-07-03"
#define MICROPY_VERSION_MAJOR (1)
#define MICROPY_VERSION_MINOR (9)
#define MICROPY_VERSION_MICRO (1)
#define MICROPY_VERSION_STRING "1.9.1"
